### ISSUE TITLE
Issue on page /scheduling/sch-simple.html

### ISSUE THREAD

**Issue by tpoimen** [OpenOSOrg/openos#12]
Under section 10.2.2 (shortest job first), there is an error with calculating the average turnaround time. Divisor should be 5 as there are 5 jobs, not 3.

Similar issue under section 10.2.3 (Round Robin). I think the average turnaround time should be (3 + 5 + 9) / 3 = 5.7

Section 10.2.2:
<img width="801" alt="image" src="https://github.com/OpenOSOrg/openos/assets/153481239/870cba1d-541e-42b3-aedf-288af97f0b27">

Section 10.2.3:
<img width="771" alt="image" src="https://github.com/OpenOSOrg/openos/assets/153481239/cefd5fdf-e03c-4363-92d9-7d638fbee9e0">

**Comment by okrieg** [comment]
Thank you, should be fixed now.
