### ISSUE TITLE
Issue on page /scheduling/sch-prio.html

### ISSUE THREAD

**Issue by Anish701** [OpenOSOrg/openos#14]
At the bottom of the page, in the section for Multilevel feedback scheduling, the bullet point "Hack to deal with starvation" is placed in "The Bad" category rather than "The Good" category. However, Multilevel feedback's ability to avoid starvation seems like a pro rather than a con.

**Comment by okrieg** [comment]
Ahh, yes, I think my point was that it is not a cleanly integrated feature, it is more a bit of a hack rather than a natural property of the algorithm.
